FROM nginx

RUN apt-get update && \
    apt-get install -y apache2-utils && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /etc/server/certs
COPY ./certs/. /etc/server
COPY ./backend-calc.nginx.conf /etc/nginx/conf.d/backend-calc.nginx.conf
COPY ./frontend-calc.nginx.conf /etc/nginx/conf.d/frontend-calc.nginx.conf

RUN htpasswd -cb /etc/server/.htpasswd AUTH 06L1tRPOY7gro3OwYP0eb8IdXmOliEtdo_i-eRsrJAqFE1bkPbc-Vg
CMD ["nginx", "-g", "daemon off;"]